name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/pyccel/psydac.git
        cd psydac
        pip install --no-dependencies .
        export PYTHONPATH="${PYTHONPATH}:@{pwd}"
        pip install jupyter-book ghp-import sphinx_proof
        python -m ipykernel install --user --name .iga-python --display-name "IGA-Python"

    - name: Build Jupyter Book
      run: jupyter-book build .

    - name: Deploy to GitHub Pages
      run: ghp-import -n -p -f _build/html
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
